### ISSUE TITLE
گزارش یک ایراد کوچک

### ISSUE THREAD

**Issue by ArdeshirV** [sadegh1998/MicroserviceShop#1]
ای بابا! این پروژه که هیچ کدی ندارد!
بخیل نباشید! دستِ کم یک TODO: و یا یک عدد:
Hello, World!\n
ساده در آن بگذارید! :D
والا!

**Comment by sadegh1998** [comment]
سلام مهندس 
وقتتون به خیر
این پروژه رو استارت زدم اما به علت مشغله کاری متاسفانه هنوز نتونستم کاراش رو انجام بدم . 
قرار بود که یک پروژه فروشگاهی رو با مایکروسرویس جهت آموزش قرار بدم.
فرمایش شما درسته ، من ریپازیتوری رو Private می کنم و یکسری کارا روش انجام می دم و مجددا public می کنم
